# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
 #  "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 7"
 #  "iPhone 7 Plus",
 #  "iPhone 8",
 #  "iPhone 8 Plus"
 ])

ios_version '10.3.1'

# erase_simulator true
 reinstall_app true
 clean true

languages([
  "en-US",
#  "de-DE",
#  "it-IT",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
 scheme "SmokeTest"

# Where should the resulting screenshots be stored?
 output_directory "/Users/mud/ToThePenny/fastlane/screenshots"

 clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
 workspace "/Users/mud/ToThePenny/Depoza.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
